### PR TITLE
843 - 844 - Missing proposals data from governance and fix incorrect rolls counts per level

### LINKED ISSUE #843: Incorrect rolls counts in governance data for batch lead block
Incorrect roll counts can be seen for some block levels on the governance data.

relates to #762 

Reported:
>when running the following query [...] with release branch r3:
>bug 1: Running the following query comes back with bad data for the yay, nay and total count and rolls `select * from tezos.governance where level between 360499 and 360505 order by level desc;`
>the block_yay_rolls column is wrong for level 360500.

Diagnosis: the rolls listing loaded during processing of block batches for the governance data storage will not include levels outside of the batch itself, which leads to the wrong values for the "lead block" in the batch, which misses previous data needed for the computation

Note: the plan is to create a fix PR for both the master branch and a back-port to the release branch

### LINKED ISSUE #844: Missing data for proposals in governance entries
Blocks with proposals seems to be missing from the governance data collected.

relates to #762 

Reported:
>when running the following query [...] with release branch r3:
>Bug #2: In the db the earliest known proposal operation is at block 332624, and the repo has the conf file stating `batchedFetches.governanceStartLevel: 350000`, the governance table only has records starting at level 360500

Diagnosis: the code collects proposal counts for all relevant blocks in a processing batch but generates data only for those having a current proposal, i.e. the proposal operations are not included, since they are from a different voting period

Note: the plan is to create a fix PR for both the master branch and a back-port to the release branch

### PR DESCRIPTION
**Pull request by ivanopagano**
Fixes #843 and #844 

The code to extract governance rows now takes all blocks into considerations, and differentiates between those that have a current proposal or not.
Hence we now have also proposals data that was not collected before.

Use stored data for rolls from the previous batch to account for the missing entry to compute per-level rolls counts.

### CODE REVIEW

File: conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala [hunk 1]
```diff
@@ -83,17 +83,25 @@ object TezosGovernanceOperations extends LazyLogging {
...
         TezosDatabaseOperations.getProposalOperationHashesByCycle(level.cycle)
     }
 
     logger.info("Searching for governance data in voting period...")
 
+    //find blocks for a specific proposal under scrutiny, relevant for counting ballots
+    val votingBlocks = proposalsBlocks.collect { case (block, Some(protocol)) => block }.toList
+
+    logger.info(
+      "There are {} blocks related to some voting - excluding proposals.",
```
Comment (vishakh) [inline conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala:97]: Let's make this a bit clearer: "There are {} blocks related to testing vote and proposal vote periods..".

Comment (ivanopagano) [reply conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala]: done, thanks

File: conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala [hunk 2]
```diff
@@ -230,17 +234,26 @@ object TezosGovernanceOperations extends LazyLogging {
...
+                )
             )
             val proposalOperationsAggregates =
-              proposalCounts.map { //these come from all individual proposal operations during the proposal period
+              proposalCounts //these come from all individual proposal operations during the proposal period
+              .filterNot {
+                /* this should never be the case: the proposal currently under evaluation
+                 * should not be proposed in operations of the same block
+                 */
+                case (proposal, _) => currentProposal.exists(_ == proposal)
```
[the remark this answers is not in the document]
Comment (ivanopagano) [reply conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala:255]: nice one

File: conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala [hunk 3]
```diff
@@ -119,8 +115,8 @@ object TezosGovernanceOperations extends LazyLogging {
     * @param ec needed to compose concurrent operations
     * @return aggregated data
     */
-  private def aggregateData(db: Database)(
-      proposalsBlocks: Map[Block, ProtocolId],
+  def aggregateData(db: Database)(
```
Comment (vishakh) [inline conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala:118]: `proposalsBlocks` and `proposalsBallots` are still ambiguous. They specifically leave out data for the proposal governance period. I would renamed them to `activeProposalsBlocks` and `activeProposalsBallots`.

File: conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala [hunk 4]
```diff
@@ -193,15 +197,15 @@ object TezosGovernanceOperations extends LazyLogging {
    * extract the numbers returning a collector object.
    */
   private def fillAggregates(
-      proposalsBlocks: Map[Block, ProtocolId],
+      proposalsBlocks: Map[Block, Option[ProtocolId]],
```
Comment (vishakh) [inline conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala:200]: `listingsPerLevel` is still too generic a name.

File: conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala [hunk 5]
```diff
@@ -193,15 +197,15 @@ object TezosGovernanceOperations extends LazyLogging {
...
       listingsPerLevel: Map[Int, List[Voting.BakerRolls]],
       ballots: Map[Block, List[Voting.Ballot]],
       ballotCountsPerLevel: Map[Block, BallotsPerLevel],
       ballotCountsPerCycle: Map[Int, BallotsPerCycle],
       proposalProtocolCounts: Map[Block, Map[ProtocolId, Int]] //comes from individual operations on the block
```
Comment (vishakh) [inline conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala:205]: `proposalProtocolCounts` is misleading. It implies we are counting the proposal operation counts by protocol ID. A better name might be something like `proposalCountsByBlock`.

File: conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala [hunk 6]
```diff
@@ -230,17 +234,26 @@ object TezosGovernanceOperations extends LazyLogging {
...
-              ballotCountPerCycle,
-              ballotCountPerLevel
+            val activeProposalAggregate = currentProposal.map(
+              proposal =>
+                GovernanceAggregate(
+                  block.data.hash,
+                  metadata,
+                  Some(proposal),
+                  allRolls,
+                  levelRolls,
```
Comment (vishakh) [inline conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala:244]: We have a bug here. The current logic is correct for the testing_vote and promotion_vote periods where we want to show the number of rolls corresponding to `ballot` operations. However, for the proposal period, we also want to show the number of rolls corresponding to `proposal` operations. We are missing the rolls counts for proposal operations here. IIUC, the column `yay_rolls` for proposal records will always be zero.

File: conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala [hunk 7]
```diff
@@ -119,8 +115,8 @@ object TezosGovernanceOperations extends LazyLogging {
     * @param ec needed to compose concurrent operations
     * @return aggregated data
     */
-  private def aggregateData(db: Database)(
-      proposalsBlocks: Map[Block, ProtocolId],
+  def aggregateData(db: Database)(
+      proposalsBlocks: Map[Block, Option[ProtocolId]],
```
Comment (vishakh) [inline conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala:119]: We probably have a bug here too. `proposalsBlocks` is ultimately derived from `TezosGovernanceOperations`, line 84:

```scala
activeProposals <- nodeOperator.getProposals(blocksInActiveVotingPeriod)
```

This only picks up blocks with active proposals. This excludes blocks from the proposal period where there is no one active proposal. When you run your local testing, you will not see any `governance` records from the proposals periods. Once you fix the bug, you will start seeing valid records for the proposals periods. Please use this as a validation of your code.

File: conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala (hunk 3 above)
Comment (ivanopagano) [reply conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala:118]: renamed

File: conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala (hunk 4 above)
Comment (ivanopagano) [reply conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala:200]: I've renamed those as `rollsByLevel` both here and in the code that pass them through

File: conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala (hunk 7 above)
Comment (ivanopagano) [reply conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala:119]: I have to disagree here: `activeProposals` collects by block any active proposal id, yet immediately after we associate those _optionally_ , with the original block list, at line 87.
That is, we associate each block with a proposal id, if there's one, otherwise the optional value is empty.

It's a sparse associative array, there are holes in the map values, corresponding to the proposal periods

Comment (ivanopagano) [reply conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala:119]: In fact I did test locally and saw those entries being saved, where previously there were none.

I can check once more, but I have logs that still shows

```
17:19:52.557 [lorre-tezos-indexer-akka.actor.default-dispatcher-40] INFO  t.c.c.i.t.TezosGovernanceOperations$ - Searching for governance data in voting period...
17:19:52.558 [lorre-tezos-indexer-akka.actor.default-dispatcher-40] INFO  t.c.c.i.t.TezosGovernanceOperations$ - There are no blocks related to some voting - excluding proposals.
17:19:53.502 [lorre-tezos-indexer-akka.actor.default-dispatcher-40] INFO  t.c.c.i.t.TezosDatabaseOperations$   - Writing 1000 governance rows into database...
```

Which attest that 1000 rows were written, even if no active voting period blocks were found

File: conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala (hunk 6 above)
Comment (ivanopagano) [reply conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala:244]: I'm asking because that's where all our rolls counts descend from.
We collect the responses of such endpoint for each block, without consider the voting period the block's been baked in.

Comment (vishakh) [reply conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala]: No, you are right. The logic is, in fact, correct!
