### PR TITLE
598 - migration to testconteiners

### LINKED ISSUE #598: Split embedded database tests from unit tests
Since the unit tests are run on each packaging, the docker build fails for some OS configuration, because the embedded DB seems to be problematic (possibly due to the underlying flapdoodle library solution).

If this proves to be the root cause, we might want to simply move the tests involving a real db process to work, into the existing `it` integration tests.

Such tests would first need be run and tested over the CI pipeline to see if everything works fine.

The ensuing codebase should also provide a smoother dev cycle, given the uTests suite would run much faster, and could be possibly parallelized too.

### PR DESCRIPTION
**Pull request by dorians**
fixes #598 (maybe)

### CODE REVIEW

**Comment by vishakh** [comment]
I am still getting build errors on Ubuntu:

```
[info] DatabaseUtilTest:
[info] Database utils query builder
[info] - should concatenate multiple values in a sql action
[info] - should concatenate an empty sequence of values in a sql action
[info] - should concatenate a singleton sequence in a sql action
[info] DataTypesTest:
[info] DataTypes
[info] - should validate correct query field
[info] - should return error with incorrect query fields
[info] - should validate correct predicate field
[info] - should return error with incorrect predicate fields
[info] - should validate correct orderBy field
[info] - should return error with incorrect orderBy fields
[info] - should validate correct aggregation field which exists in DB
[info] - should return error with incorrect aggregation field which exists in DB
[info] - should return two errors when we try to aggregate on non-aggregating field type and with field that does not exist in query fields
[info] - should return error with when none of the fields in predicates are valid for querying
[info] - should successfully validates aggregation for any dataType when COUNT function is used
[info] - should correctly transform predicate DateTime field as Long into ISO
[info] - should correctly validate query when aggregated field is used in orderBy
[info] - should correctly validate query when aggregated field is used in predicate
[info] - should correctly aggregate field with currency data type
[info] - should return validation error when formatting is being done on non-DateTime field
[info] - should correctly validate field with format
[info] - should return invalid snapshot field
[info] CollectionOpsTest:
[info] Collection operations
[info] - should allow grouping over sequences of tuples
[info] - should provide extension syntax to group over sequences of tuples
[info] - should allow to define operations on bounds for a non-empty collection
[info] - should allow to define operations on bounds for an empty collection, returning an empty value
[info] - should provide extension syntax to call operations on bounds for a non-empty collection
[info] - should provide extension syntax to call operations on bounds for an empty collection, returning an empty value
[info] TezosNodeOperatorTest:
[info] getBlock
[info] - should correctly fetch the genesis block
[info] getLatestBlocks
[info] - should correctly fetch all the blocks if no depth is passed-in
[info] getLatestBlocks
[info] - should correctly fetch latest blocks
[info] getLatestBlocks
[info] - should correctly fetch blocks starting from a given head
[info] JsonDecodersTest:
[info] the json decoders
[info] - should allow decoding json with duplicate fields
[info] - should decode null fields as empty Options
[info] - should decode a timestamp from ISO-8601 string format
[info] - should decode valid json base58check strings into a PublicKey
[info] - should fail to decode an invalid json base58check strings into a PublicKey
[info] - should decode valid json base58check strings into a PublicKeyHash
[info] - should fail to decode an invalid json base58check strings into a PublicKeyHash
[info] - should decode valid json base58check strings into a Signature
[info] - should fail to decode an invalid json base58check strings into a Signature
[info] - should decode valid json base58check strings into a BlockHash
[info] - should fail to decode an invalid json base58check strings into a BlockHash
[info] - should decode valid json base58check strings into a OperationHash
[info] - should fail to decode an invalid json base58check strings into a OperationHash
[info] - should decode valid json base58check strings into a AccountId
[info] - should fail to decode an invalid json base58check strings into a AccountId
[info] - should decode valid json base58check strings into a ContractId
[info] - should fail to decode an invalid json base58check strings into a ContractId
[info] - should decode valid json base58check strings into a ChainId
[info] - should fail to decode an invalid json base58check strings into a ChainId
[info] - should decode valid json base58check strings into a ProtocolId
[info] - should fail to decode an invalid json base58check strings into a ProtocolId
[info] - should decode valid json base58check strings into a ScriptId
[info] - should fail to decode an invalid json base58check strings into a ScriptId
[info] - should decode valid json alphanumneric strings into a Nonce
[info] - should fail to decode an invalid json alphanumneric strings into a Nonce
[info] - should decode valid json base58check strings into a NonceHash
[info] - should fail to decode an invalid json base58check strings into a NonceHash
[info] - should decode valid json alphanumneric strings into a Secret
[info] - should fail to decode an invalid json alphanumneric strings into a Secret
[info] - should decode valid json into Micheline values
[info] - should fail to decode invalid json into Micheline values
[info] - should decode valid json strings representing a PositiveBigNumber
[info] - should decode valid json strings representing zero as a PositiveBigNumber
[info] - should decode invalid json for PositiveBigNumber, representing negatives, as the original string
[info] - should decode invalid json for PositiveBigNumber, not representing numbers, as the original string
[info] - should decode valid json strings representing both positive and negative values as BigNumber
[info] - should decode invalid json for BigNumber, not representing numbers, as the original string
[info] - should decode all valid voting period kinds to an enumerated value
[info] - should fail to decode an invalid string as a voting period kind
[info] - should decode all valid ballot votes to a BallotVote
[info] - should fail to decode an invalid string to a BallotVote
[info] - should decode valid json into a BigMapDiff value
[info] - should decode valid json into a Scipted.Contracts value
[info] - should decode valid json into Error values
[info] - should fail to decode invalid json into Error values
[info] - should decode an endorsement operation from json
[info] - should decode a seed nonce revelation operation from json
[info] - should decode an account activation operation from json
[info] - should decode an reveal operation from json
[info] - should decode an transaction with internal transaction result operation from json
[info] - should decode an origination operation from json
[info] - should decode an origination operation from alphanet schema json
[info] - should decode a delegation operation from json
[info] - should decode a group of operations from json
[info] - should decode proposals elements
[info] - should decode bakers rolls
[info] - should decode bakers rolls even if rolls are json encoded as 'stringly' numbers
[info] - should fail to decode bakers rolls for invalid fields
[info] - should decode ballots
[info] - should fail to decode ballots with invalid fields
[info] - should decode accounts
[info] - should decode legacy protocol4 accounts
[info] - should decode account scripts as wrapped and unparsed text, instead of a json object
[info] - should decode a delegate baker
[info] - should decode delegate contracts
[info] MetadataServiceTest:
[info] The metadata service
[info] - should fetch the list of supported platforms
[info] - should override the display name for a platform
[info] - should override description for a platform
[info] - should filter out disabled platform
[info] - should filter out disabled platform (default behaviour)
[info] - should fetch the list of supported networks
[info] - should override the display name for a network
[info] - should override description for a network
[info] - should filter out a hidden network
[info] - should return None when fetching network for a non existing platform
[info] - should return None when fetching networks for a hidden platform
[info] - should return None when fetching networks for a hidden platform (by default)
[info] - should fetch the list of supported entities
[info] - should fetch the list of supported entities with updated values
[info] - should override the display name for an entity
[info] - should override the display name plural for an entity
[info] - should override description for an entity
[info] - should filter out a hidden entity
[info] - should filter out a hidden entity (by default)
[info] - should filter out a hidden entity (by default) with updated entities
[info] - should return None when fetching entities for a non existing platform
[info] - should return None when fetching entities for a hidden platform
[info] - should return None when fetching entities for a non existing network
[info] - should return None when fetching entities for a hidden network
[info] - should fetch the list of supported attributes
[info] - should fetch the list of supported attributes with updated values
[info] - should override additional fields for an attribute
[info] - should filter out a hidden attribute
[info] - should filter out a hidden attribute (bu default)
[info] - should return None when fetching attributes for a non existing platform
[info] - should return None when fetching attributes for a hidden platform
[info] - should return None when fetching attributes for a non existing network
[info] - should return None when fetching attributes for a hidden network
[info] - should return None when fetching attributes for a non existing entity
[info] - should return None when fetching attributes for a hidden entity
[info] DataTest:
[info] Query protocol
[info] - should return a correct response with OK status code with POST
[info] - should return 404 NotFound status code for request for the not supported platform with POST
[info] - should return 404 NotFound status code for request for the not supported network with POST
[info] - should return a correct response with OK status code with GET
[info] - should return 404 NotFound status code for request for the not supported platform with GET
[info] - should return 404 NotFound status code for request for the not supported network with GET
[info] AppInfoRouteTest:
[info] The application info route
[info] - should expose an endpoint to get the current application version
[info] - should reject any other http method than GET
[info] JsonToMichelsonSpec:
[info] A JsonToMichelson
[info] - should convert json to michelson format
[info] JsonUtilTest:
[info] JsonUtil
[info] - should expose a JsonString empty object
[info] - should allow wrapping of valid json into a JsonString
[info] - should fail when wrapping invalid json into a JsonString
[info] - should sanitize unwanted input, by removing any ISO control char from the json string
[info] - should sanitize unwanted input, by removing any string-encoded unicode chars from the json string
[info] - should convert a simple map to json
[info] - should convert a complex map to json
[info] - should convert a simple json to a map
[info] - should convert a complex json to a map
[info] - should allow lenient parsing of json with duplicate object keys, actually deserialized or not
[info] AccountIds unapply object
[info] - should match a valid account id
[info] - should extract the valid account ids from a json string
[info] - should not extract a valid hash format as part of another value in a json string
[info] - should not match when no valid hash was found
[info] SecurityTest:
[info] The SecurityApi
[info] - should valid itself
[info] - should validate a given key
[info] CryptoUtilTest:
[info] CryptoUtilTest
[info] - should correctly decode and encode a Tezos account ID
[info] CryptoUtilTest
[info] - should correctly decode and encode a Tezos operation ID
[info] MichelsonRendererSpec:
[info] - should render single MichelsonType
[info] - should render one-argument MichelsonType
[info] - should render two-argument MichelsonType
[info] - should render MichelsonType with int constant
[info] - should render MichelsonType with string constant
[info] - should render MichelsonType with string constant including JSON
[info] - should render MichelsonType with bytes constant
[info] - should render MichelsonType with annotation
[info] - should render complex MichelsonType
[info] - should render MichelsonCode with only one simple instruction
[info] - should render MichelsonCode with two simple instructions
[info] - should render MichelsonCode with typed instruction
[info] - should render MichelsonCode with typed instruction with constant
[info] - should render MichelsonCode with instruction sequence
[info] - should render MichelsonCode with complex instruction
[info] - should render MichelsonInstruction with empty embedded instruction
[info] - should render MichelsonInstruction IF
[info] - should render MichelsonInstruction with embedded IF-s
[info] - should render empty MichelsonSchema
[info] - should render MichelsonInstruction with an annotation
[info] - should render complex MichelsonCode
[info] TezosTypesTest:
[info] The Base58Check verifier
[info] - should accept an empty string
[info] - should accept a correctly encoded string
[info] - should reject a string with forbidden chars
[info] - should reject a string with spaces
[info] The Syntax import
[info] - should allow building Block-tagged generic data
[info] The BlockTagged wrapper
[info] - should convert to a tuple
[info] The lenses for tezos types
[info] - should modify parameters with monocle's lenses
[info] - should modify storage with monocle's lenses
[info] - should modify code with monocle's lenses
[info] The TezosOptics
[info] - should allow to read existing code within an account
[info] - should read None if there's no script in an account
[info] - should allow to update an existing script within an account
[info] JsonParserSpec:
[info] - should parse one-argument MichelsonType
[info] - should parse two-argument MichelsonType
[info] - should parse complex MichelsonType
[info] - should parse MichelsonType with annotation
[info] - should parse MichelsonInstruction with only one simple instruction
[info] - should parse MichelsonInstructionSequence
[info] - should parse typed MichelsonInstruction
[info] - should parse MichelsonInstruction with annotation
[info] - should parse complex MichelsonInstruction
[info] - should parse MichelsonInstruction typed with int data
[info] - should parse MichelsonInstruction typed with string data
[info] - should parse MichelsonInstruction typed with bytes data
[info] - should parse double embedded MichelsonInstruction
[info] - should parse empty MichelsonInstruction
[info] - should parse empty MichelsonInstruction when it appears alone
[info] - should parse empty MichelsonExpression
[info] - should parse LAMBDA MichelsonInstruction
[info] - should parse MichelsonExpression with both MichelsonExpression and MichelsonInstruction as arguments
[info] - should parse MichelsonInstruction represented as simple string
[info] - should convert simplest json to MichelsonSchema
[info] - should parse MichelsonCode
[info] - should give meaningful error in case of json without parameter section
[info] - should give meaningful error in case of json without code section
[info] - should parse empty schema
[info] - should convert complex json to MichelsonSchema
        ℹ︎ Checking the system...
        ✔ Docker version should be at least 1.6.0
        ✘ Docker environment should have more than 2GB free disk space
[info] ApiOperationsTest:
[info] tech.cryptonomic.conseil.tezos.ApiOperationsTest *** ABORTED ***
[info]   java.lang.AssertionError: Docker environment should have more than 2GB free disk space
[info]   at org.rnorth.visibleassertions.VisibleAssertions.fail(VisibleAssertions.java:437)
[info]   at org.rnorth.visibleassertions.VisibleAssertions.assertTrue(VisibleAssertions.java:129)
[info]   at org.testcontainers.DockerClientFactory.checkDiskSpace(DockerClientFactory.java:191)
[info]   at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:140)
[info]   at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:51)
[info]   at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:27)
[info]   at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:20)
[info]   at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:27)
[info]   at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1151)
[info]   at org.testcontainers.containers.GenericContainer.setDockerImageName(GenericContainer.java:1141)
[info]   ...
[info] MetadataCachingTest:
[info] Metadata caching
[info] - should get initial state of caching status
[info] - should update cache status
[info] - should init attributes cache
[info] - should init entities cache
[info] - should init attribute values cache
[info] - should insert/update values in entities cache
[info] - should insert/update values in attributes cache
[info] - should insert/update values in attribute values cache
[info] PlatformDiscoveryTest:
[info] The platform discovery route
[info] - should expose an endpoint to get the list of supported platforms
[info] - should should filter out hidden platforms
[info] - should should rename platform's display name and description
[info] - should expose an endpoint to get the list of supported networks
[info] - should expose an endpoint to get the list of supported entities
[info] - should expose an endpoint to get the list of supported attributes
[info] - should override additional data for attributes
[info] - should return 404 on getting attributes when parent entity is not enabled
[info] - should return 404 on getting attributes when parent network is not enabled
[info] - should return 404 on getting attributes when parent platform is not enabled
[info] RetryTest:
[info] Future
[info] - should return value if block succeeds without retry
[info] - should return value if block succeeds with retry
[info] - should throw TooManyRetriesException (with cause) if block fails and no retry is allowed
[info] - should throw TooManyRetriesException (with cause) if all retries are used up
[info] Number of Attempts
[info] - should execute block exactly once if first attempt passes
[info] - should execute block 2 times if first attempt fails
[info] - should execute block 3 times if earlier attempts fail
[info] - should execute block exactly once if max #retries is zero
[info] - should be unlimited if max #retries is none
[info] Deadline
[info] - should not be exceeded by retries
[info] - should throw DeadlineExceededException (with cause) if exceeded
[info] Give Up On Selected Exceptions
[info] - should not retry if selected exception is seen in 1st attempt
[info] - should retry until selected exception is seen
[info] - should retry normally if selected exception is never seen
[info] ConfigUtilTest:
[info] the config.Natural matcher
[info] - should match a valid positive integer string
[info] - should refuse a zero integer string
[info] - should refuse a negatige integer string
[info] - should refuse a non-numeric string
[info] ConfigUtil
[info] - should adapt multiple pureconfig reader failures to a single reason
[info] - should fold many parse results into a single failure if any is present
[info] - should extract the correct platforms type
[info] - should extract the correct configuration map for Tezos platform's networks
[info] - should extract a configuration map that includes a unknown platforms
[info] - should extract the client host pool configuration for streaming http
[info] - should fail to extract the client host pool configuration with the wrong namespace
[info] MathUtilTest:
[info] MathUtilTest
[info] - should correctly calculate the mean of a sequence
[info] MathUtilTest
[info] - should correctly calculate the population standard deviation of a sequence
[info] MathUtilTest
[info] - should correctly calculate the population standard deviation of a sequence corrected for using samples
[info] TezosDatabaseOperationsTest:
[info] The database api
[info] - should write fees
[info] - should tell if there are any stored blocks
[info] - should write blocks
[info] - should write metadata balance updates along with the blocks
[info] - should write accounts for a single block
[info] - should fail to write accounts if the reference block is not stored
[info] - should update accounts if they exists already
[info] - should store checkpoint account ids with block reference
[info] - should clean the accounts checkpoints with no selection
[info] - should clean the accounts checkpoints with a partial id selection
[info] - should write delegates for a single block
[info] - should fail to write delegates if the reference block is not stored
[info] - should update delegates if they exists already
[info] - should store checkpoint delegate key hashes with block reference
[info] - should clean the delegates checkpoints with no selection
[info] - should clean the delegates checkpoints with a partial key hash selection
[info] - should read latest account ids from checkpoint
[info] - should read latest delegate key hashes from checkpoint
[info] - should fetch nothing if looking up a non-existent operation group by hash
[info] - should fetch existing operations with their group on a existing hash
[info] - should compute correct average fees from stored operations
[info] - should return None when computing average fees for a kind with no data
[info] - should compute average fees only using the selected operation kinds
[info] - should write voting bakers rolls
[info] - should return the default when fetching the latest block level and there's no block stored
[info] - should fetch the latest block level when blocks are available
[info] - should correctly verify when a block exists
[info] - should say a block doesn't exist if it has no associated operation group
[info] - should get all values from the table with nulls as nones
[info] - should get values where context is null
[info] - should get values where context is NOT null
[info] - should get null values from the table as none
[info] - should get map from a block table
[info] - should get map from a block table with predicate
[info] - should get map from a block table with inverse predicate
[info] - should get map from a block table with multiple predicates
[info] - should get map from a block table with multiple predicate groups
[info] - should get empty map from empty table
[info] - should get map from a block table with eq predicate
[info] - should get map from a block table with eq predicate on numeric type
[info] - should get map from a block table with like predicate when starts with pattern
[info] - should get map from a block table with like predicate when ends with pattern
[info] - should get map from a block table with like predicate when pattern is in the middle
[info] - should get map from a block table with less than predicate when one element fulfils it
[info] - should get empty map from a block table with less than predicate when no elements fulfil it
[info] - should get map from a block table with between predicate when two element fulfill it
[info] - should get map from a block table with between predicate when two element fulfill it but limited to 1 element
[info] - should get map from a block table with between predicate when one element fulfill it
[info] - should get map from a block table with datetime field
[info] - should get map from a block table with startsWith predicate
[info] - should get empty map from a block table with startsWith predicate
[info] - should get map from a block table with endsWith predicate
[info] - should get empty map from a block table with endsWith predicate
[info] - should get one element when correctly rounded value
[info] - should get empty list of elements when correctly rounded value does not match
[info] - should return the same results for the same query
[info] - should get map from a block table and sort by level in ascending order
[info] - should get map from a block table and sort by level in descending order
[info] - should get map from a block table and sort by hash in descending order
[info] - should get map from a block table and sort by hash in ascending order
[info] - should get map from a block table and sort by proto in descending order and by level in ascending order
[info] - should should aggregate with COUNT function
[info] - should should aggregate with MAX function
[info] - should should aggregate with MIN function
[info] - should should aggregate with SUM function
[info] - should should aggregate with SUM function and order by SUM()
[info] - should should order correctly by the field not existing in query)
[info] - should should correctly check use between in the timestamps
[info] - should should correctly execute BETWEEN operation using numeric comparison instead of lexicographical
[info] - should should return correct query when asked for SQL
[info] - should should aggregate with multiple aggregations on the same field
[info] - should should aggregate with single aggegation when there is only one field
[info] - should should aggregate with correct predicate field when aggregation is using predicate
[info] - should should aggregate correctly with multiple aggregation fields with predicate
[info] - should should aggregate with datePart aggregation *** FAILED ***
[info]   List(Map("count_medium" -> Some(3), "date_part_timestamp" -> Some("1970-01-01")), Map("count_medium" -> Some(2), "date_part_timestamp" -> Some("1970-01-02")), Map("count_medium" -> Some(1), "date_part_timestamp" -> Some("1969-12-31"))) was not equal to List(Map("date_part_timestamp" -> Some("1970-01-02"), "count_medium" -> Some(3)), Map("date_part_timestamp" -> Some("1970-01-03"), "count_medium" -> Some(2)), Map("date_part_timestamp" -> Some("1970-01-01"), "count_medium" -> Some(1))) (TezosDatabaseOperationsTest.scala:2998)
[info] - should should map date with datePart aggregation when it is only type of aggregation *** FAILED ***
[info]   List(Map("date_part_timestamp" -> Some("1970-01-02")), Map("date_part_timestamp" -> Some("1970-01-02")), Map("date_part_timestamp" -> Some("1970-01-01")), Map("date_part_timestamp" -> Some("1970-01-01")), Map("date_part_timestamp" -> Some("1970-01-01")), Map("date_part_timestamp" -> Some("1969-12-31"))) was not equal to List(Map("date_part_timestamp" -> Some("1970-01-03")), Map("date_part_timestamp" -> Some("1970-01-03")), Map("date_part_timestamp" -> Some("1970-01-02")), Map("date_part_timestamp" -> Some("1970-01-02")), Map("date_part_timestamp" -> Some("1970-01-02")), Map("date_part_timestamp" -> Some("1970-01-01"))) (TezosDatabaseOperationsTest.scala:3034)
[info] - should should correctly use query on temporal table
[info] - should should get the balance of an account at a specific timestamp where there are multiple entities for given account_id
[info] - should should get the balance of an account at a specific timestamp
[info] DatabaseConversionsTest:
[info] The database conversion
[info] - should correctly convert a positive bignumber valued '0' from tezos models to a BigDecimal value
[info] - should correctly convert a positive bignumber from tezos models to a BigDecimal value
[info] - should give no result when converting invalid positive bignumbers from tezos models to a BigDecimal value
[info] - should correctly convert a bignumber from tezos models to a BigDecimal value
[info] - should give no result when converting invalid bignumbers from tezos models to a BigDecimal value
[info] - should convert a tezos genesis block to a database row
[info] - should convert a tezos block to a database row
[info] - should convert Balance Updates in BlockData to a database row
[info] - should convert Balance Updates in Operations to a database row
[info] - should convert Balance Updates in all nested levels of Operations to a database row
[info] - should convert an Endorsement to a database row
[info] - should convert a SeedNonceRevelation to a database row
[info] - should convert an ActivateAccount to a database row
[info] - should convert a Reveal to a database row
[info] - should convert a Transaction to a database row
[info] - should convert an Origination to a database row
[info] - should convert an Delegation to a database row
[info] - should convert an DoubleEndorsementEvidence to a database row
[info] - should convert an DoubleBakingEvidence to a database row
[info] - should convert a Proposals operation to a database row
[info] - should convert a Ballot operation to a database row
[info] - should convert a Voting Baker to a database row
[info] CsvConversionsTest:
[info] CSV conversions
[info] - should correctly convert List[QueryResponse] to CsvString
[info] - should correctly convert empty list
[info] TezosPlatformDiscoveryOperationsTest:
[info] getNetworks
[info] - should return list with one element
[info] - should return two networks
[info] getEntities
[info] - should return list of attributes of Fees
[info] - should return list of attributes of accounts
[info] - should return list of attributes of blocks
[info] - should return list of attributes of operations
[info] - should return list of attributes of operation groups
[info] - should return list of attributes of delegates
[info] - should return list of attributes of rolls
[info] - should return empty list for non existing table
[info] listAttributeValues
[info] - should return list of values of kind attribute of Fees without filter
[info] - should return list of boolean values
[info] - should returns a list of errors when asked for medium attribute of Fees without filter - numeric attributes should not be displayed
[info] - should return list with one error when the minimum matching length is greater than match length
[info] - should return empty list when trying to sql inject
[info] - should correctly apply the filter
[info] Run completed in 55 seconds, 38 milliseconds.
[info] Total number of tests run: 381
[info] Suites: completed 24, aborted 1
[info] Tests: succeeded 379, failed 2, canceled 0, ignored 0, pending 0
[info] *** 1 SUITE ABORTED ***
[info] *** 2 TESTS FAILED ***
[error] Failed tests:
[error]         tech.cryptonomic.conseil.tezos.TezosDatabaseOperationsTest
[error] Error during tests:
[error]         tech.cryptonomic.conseil.tezos.ApiOperationsTest
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 139 s, completed Nov 12, 2019, 8:30:14 PM
```

**Comment by ivanopagano** [comment]
> [info] - should convert complex json to MichelsonSchema
>         ℹ︎ Checking the system...
>         ✔ Docker version should be at least 1.6.0
>         ✘ Docker environment should have more than 2GB free disk space
> [info] ApiOperationsTest:

Can you allocate more memory to the Docker runtime?

**Comment by vishakh** [comment]
@ivanopagano @dorians I also have these failures:

```
[info] - should should aggregate with datePart aggregation *** FAILED ***
[info]   List(Map("count_medium" -> Some(3), "date_part_timestamp" -> Some("1970-01-01")), Map("count_medium" -> Some(2), "date_part_timestamp" -> Some("1970-01-02")), Map("count_medium" -> Some(1), "date_part_timestamp" -> Some("1969-12-31"))) was not equal to List(Map("date_part_timestamp" -> Some("1970-01-02"), "count_medium" -> Some(3)), Map("date_part_timestamp" -> Some("1970-01-03"), "count_medium" -> Some(2)), Map("date_part_timestamp" -> Some("1970-01-01"), "count_medium" -> Some(1))) (TezosDatabaseOperationsTest.scala:2998)
[info] - should should map date with datePart aggregation when it is only type of aggregation *** FAILED ***
[info]   List(Map("date_part_timestamp" -> Some("1970-01-02")), Map("date_part_timestamp" -> Some("1970-01-02")), Map("date_part_timestamp" -> Some("1970-01-01")), Map("date_part_timestamp" -> Some("1970-01-01")), Map("date_part_timestamp" -> Some("1970-01-01")), Map("date_part_timestamp" -> Some("1969-12-31"))) was not equal to List(Map("date_part_timestamp" -> Some("1970-01-03")), Map("date_part_timestamp" -> Some("1970-01-03")), Map("date_part_timestamp" -> Some("1970-01-02")), Map("date_part_timestamp" -> Some("1970-01-02")), Map("date_part_timestamp" -> Some("1970-01-02")), Map("date_part_timestamp" -> Some("1970-01-01"))) (TezosDatabaseOperationsTest.scala:3034)
```

**Comment by vishakh** [comment]
@ivanopagano I don't understand why Docker needs 2 GB+ of free space to run unit tests.

**Comment by ivanopagano** [comment]
> @ivanopagano I don't understand why Docker needs 2 GB+ of free space to run unit tests.

I'm only referring to the failing pre-check list above. I'm assuming that comes from the testcontainers library. I think they did some testing to verify how much memory was consumed on average by the docker containers.

File: src/test/scala/tech/cryptonomic/conseil/tezos/InMemoryDatabase.scala [hunk 1]
```diff
@@ -39,15 +38,6 @@ trait InMemoryDatabase extends BeforeAndAfterAll with BeforeAndAfterEach {
...
 
-  /* turns off anti-corruption guarantees settings that will improve performance on testing
-   * override to change or add test-specific settings
-   */
-  protected val pgInitParams = List("--nosync", "--lc-collate=C")
-  /* turns off anti-corruption guarantees settings that will improve performance on testing
-   * override to change or add test-specific settings
-   */
-  protected val pgConfigs = List("-c", "full_page_writes=off")
-
```
Comment (ivanopagano) [inline src/test/scala/tech/cryptonomic/conseil/tezos/InMemoryDatabase.scala]: I guess we remove these because they were only available to the embedded pg library?
