### PR TITLE
499 - fix for the aggregation validation

### LINKED ISSUE #499: Aggregation does not work for currency type fields
With the update adding another type of the field we forgot to add `Currency` to the data types validation, for the types which could be used with sum/max/min/avg aggregations.

### PR DESCRIPTION
**Pull request by piotrkosecki**
fixes #499 

Removed unused ExecutionContext and used scalafmt formatting

### CODE REVIEW

File: src/main/scala/tech/cryptonomic/conseil/tezos/michelson/renderer/MichelsonRenderer.scala [hunk 1]
```diff
@@ -52,7 +52,7 @@ object MichelsonRenderer {
       self
         .map(_.render())
         .mkString(" ;\n")
-        .lines
+        .linesIterator
```
Comment (ba205) [inline src/main/scala/tech/cryptonomic/conseil/tezos/michelson/renderer/MichelsonRenderer.scala]: Really interesting history here, linesIterator was deprecated because it had the same functionality at lines, then undeprecated because lines conflicted with other Scala functions. How does this impact aggregation?

Comment (piotrkosecki) [reply src/main/scala/tech/cryptonomic/conseil/tezos/michelson/renderer/MichelsonRenderer.scala]: it does not impact aggregation directly, but because of that travis did not want to build the project and run tests
