### PR TITLE
570 - fix for the endorsing/baking rights

### LINKED ISSUE #570: Fetching endorsing/baking operations fails because of connections limit in Lorre
The issue can be resolved with using batched queries for fetching baking/endorsing rights with given block.

### PR DESCRIPTION
**Pull request by piotrkosecki**
resolves #570 

Changed way of fetching endorsing rights. Now they are being batched.

### CODE REVIEW

File: src/main/scala/tech/cryptonomic/conseil/tezos/TezosTypes.scala [hunk 1]
```diff
@@ -531,14 +531,15 @@ object TezosTypes {
       level: Int,
       delegate: String,
       priority: Int,
-      estimated_time: java.sql.Timestamp
+      estimated_time: ZonedDateTime
```
Comment (bhaskarkishore) [inline src/main/scala/tech/cryptonomic/conseil/tezos/TezosTypes.scala]: Curious, Why have we moved away from simple timestamps?

Comment (ivanopagano) [reply src/main/scala/tech/cryptonomic/conseil/tezos/TezosTypes.scala]: I've suggested this to keep the domain model clean of things related to a database.
This helps immediately to decode json datetimes with no custom decoding definitions, and allows (if ever needed) more handle to operate on the datetime values.
