### PR TITLE
423 - fix for incorrect validation of aggregation prefixes in predicates and orderBy

### LINKED ISSUE #423: Validating orderBy and predicates does not work after renaming columns in aggregation.
In PR for ticket #390 I've added renaming of the aggregation fields to contain prefix like `count_`, `sum_` etc, but I did not change the validation and queries trying to order by `sum_<field>` or filter using predicates are failing during validation.

### PR DESCRIPTION
**Pull request by piotrkosecki**
resolves #423

### CODE REVIEW

File: src/main/scala/tech/cryptonomic/conseil/generic/chain/DataTypes.scala [hunk 1]
```diff
@@ -71,6 +72,18 @@ object DataTypes {
...
 
+  /** Drops aggregation prefixes from field name */
+  private def dropAggregationPrefixes(fieldName: String): String = {
+    dropAnyOfPrefixes(fieldName, AggregationType.values.toList.map(_.toString + "_"))
+  }
+
+  /** Helper method for dropping prefixes from given string */
+  private def dropAnyOfPrefixes(str: String, prefixes: List[String]): String = {
+    prefixes.collectFirst {
+      case prefixToBeDropped if str.startsWith(prefixToBeDropped) => str.drop(prefixToBeDropped.length)
```
Comment (ivanopagano) [inline src/main/scala/tech/cryptonomic/conseil/generic/chain/DataTypes.scala]: `str.stripPrefix(prefixToBeDropped)` also

File: src/main/scala/tech/cryptonomic/conseil/generic/chain/DataTypes.scala [hunk 2]
```diff
@@ -71,6 +72,18 @@ object DataTypes {
     }
   }
 
+  /** Drops aggregation prefixes from field name */
+  private def dropAggregationPrefixes(fieldName: String): String = {
+    dropAnyOfPrefixes(fieldName, AggregationType.values.toList.map(_.toString + "_"))
```
[the remark this answers is not in the document]
Comment (piotrkosecki) [reply src/main/scala/tech/cryptonomic/conseil/generic/chain/DataTypes.scala]: I've added method `prefixes` in enumeration object, WDYT?

File: src/main/scala/tech/cryptonomic/conseil/generic/chain/DataTypes.scala (hunk 1 above)
Comment (piotrkosecki) [reply src/main/scala/tech/cryptonomic/conseil/generic/chain/DataTypes.scala]: ok, changed
