### PR TITLE
187-2 forked data invalidation

### LINKED ISSUE #894: Bakers information on accounts is suspected to be inaccurate
During routine development it came out that stored bakers information for each block is incorrectly fetched when updating the downloaded accounts' baking information.
The baker rolls are matched to blocks via their pkh instead of by block reference.

Fix: correct the wrong reference match.

### PR DESCRIPTION
**Pull request by ivanopagano**
This is part of the multi-step feature in #187 and basically #42 

Additionally fixes #894 

This specific PR introduces two columns to tezos database blocks and all entities that might be invalidated by a fork:
 * invalidatedAsof a date of invalidation
 * forkId identifies the fork on which the data is "living"

The forkId is always filled, by default with an identifier which conventionally denotes the valid fork, otherwise by randomly generated strings.

The PR introduces the relevant changes to data and a whole suite of tests that makes impossible for application clients to see any data that is marked as being invalidated by a fork.

This is in preparation for the fork-correction logic that will mark as invalid all data that is identified as part of a forked branch of the blockchain.
Such data is not intended to reach the client applications for the moment.
Later we want to introduce specific means to query the data for forks and invalidated data information

### Pending considerations

The current solution doesn't directly handle events like the airdrop update that marks some events as being processed.
This processed events registry will be cleaned correctly by the fork-handling algorithm as an active operation.

As a last note `BigMapsOperations` is generally hard to figure out
It's based on operations that result in diffs.
Invalidated operations should reset the values stored in the map contents, or even the map itself or any modification thereof
This is still an open problem

## Changes to the database schema
The following columns are added for the tables listed right below

Columns
 * `invalidated_asof timestamp`
 * `fork_id character varying NOT NULL`

Impacted Tables
 * tezos.blocks (and declares `UNIQUE (hash, fork_id)`)
 * tezos.accounts (and declares `PRIMARY_KEY (account_id, fork_id)`)
 * tezos.accounts_history
 * tezos.bakers (and declares `PRIMARY_KEY (pkh, fork_id)`)
 * tezos.bakers_history
 * tezos.operation_groups (and declares `PRIMARY_KEY (block_id, hash, fork_id)`)
 * tezos.operations (and declares `PRIMARY_KEY (operation_id, fork_id)`)
 * tezos.governance (the PRIMARY_KEY now has `fork_id` as additional column)
 * tezos.balance_updates (and declares `PRIMARY_KEY (id, fork_id)`)
 * tezos.token_balances (the PRIMARY_KEY now has `fork_id` as additional column)
 * tezos.baking_rights (and declares `PRIMARY_KEY (block_level, delegate, fork_id)`)
 * tezos.endorsing_rights (and declares `PRIMARY_KEY (block_level, delegate, slot, fork_id)`)
 * tezos.fees

The following foreign keys where impacted as declared below

```sql
ALTER TABLE ONLY tezos.accounts
    ADD CONSTRAINT accounts_block_id_fkey FOREIGN KEY (block_id, fork_id) REFERENCES tezos.blocks(hash, fork_id);

ALTER TABLE ONLY tezos.operation_groups
    ADD CONSTRAINT block FOREIGN KEY (block_id, fork_id) REFERENCES tezos.blocks(hash, fork_id);

ALTER TABLE ONLY tezos.bakers
    ADD CONSTRAINT bakers_block_id_fkey FOREIGN KEY (block_id, fork_id) REFERENCES tezos.blocks(hash, fork_id);

ALTER TABLE ONLY tezos.baking_rights
    ADD CONSTRAINT fk_block_hash FOREIGN KEY (block_hash, fork_id) REFERENCES tezos.blocks(hash, fork_id) NOT VALID;

ALTER TABLE ONLY tezos.endorsing_rights
    ADD CONSTRAINT fk_block_hash FOREIGN KEY (block_hash, fork_id) REFERENCES tezos.blocks(hash, fork_id) NOT VALID;

ALTER TABLE ONLY tezos.operations
    ADD CONSTRAINT fk_blockhashes FOREIGN KEY (block_hash, fork_id) REFERENCES tezos.blocks(hash, fork_id);

ALTER TABLE ONLY tezos.operations
    ADD CONSTRAINT fk_opgroups FOREIGN KEY (operation_group_hash, block_hash, fork_id) REFERENCES tezos.operation_groups(hash, block_id, fork_id);
```

Any reference to primary keys is now declared in the table definition in the most recent schema sql file

### CODE REVIEW

File: conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/bigmaps/BigMapsOperations.scala [hunk 1]
```diff
@@ -388,7 +388,8 @@ case class BigMapsOperations[Profile <: ExPostgresProfile](profile: Profile) ext
                 balance = BigDecimal(tokenUpdate.balance),
                 blockId = blockData.hash.value,
                 blockLevel = blockData.header.level,
-                asof = toSql(blockData.header.timestamp)
+                asof = toSql(blockData.header.timestamp),
+                forkId = Fork.mainForkId
```
Comment (piotrkosecki) [inline conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/bigmaps/BigMapsOperations.scala:392]: I'm probably missing something, but how do we verify that this will be `mainForkId`?

Comment (piotrkosecki) [reply conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/bigmaps/BigMapsOperations.scala:392]: never mind 😄 I just realised it will be invalidated when the time comes.

File: conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/ApiDataOperations.scala [hunk 2]
```diff
@@ -78,24 +78,68 @@ trait ApiDataOperations extends DatabaseMetadataOperations with DataOperations {
...
+    * Defaults to an empty set.
+    */
+  protected def forkRelatedFields: Set[String] = Set.empty
+
+  /** Generates extra predicates to skip whole records that would make the fork logic apparent in results.
+    * A common implementation will add a filter on the "invalidation flag/date" field to be empty or false.
+    *
+    * Defaults to an empty list.
+    */
+  protected def hideForkResults(userQueryPredicates: List[Predicate]): List[Predicate] = List.empty
```
Comment (piotrkosecki) [inline conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/ApiDataOperations.scala:130]: I'm not sure why it defaults to empty list. Are you going to add a predicate that checks if row was invalidated later?

Comment (ivanopagano) [reply conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/ApiDataOperations.scala:130]: Maybe I misread the question.
The actual implementation will add an additional predicate for the "invalidated_asof" column to be null.

Such implementation is currently custom to the tezos schema. Other chains will use the default empty predicate list, so that the queries will not be impacted for now.
I assume that we'll later apply a similar forking algorithm to ethereum and bitcoin too, but I'm not doing that right now, for lack of details.

Comment (piotrkosecki) [reply conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/ApiDataOperations.scala:130]: oh, ok! My mind defaulted to the tezos only implementation. That explains a lot, thanks! 😄

File: conseil-common/src/main/scala/tech/cryptonomic/conseil/common/tezos/Fork.scala [hunk 3]
```diff
@@ -0,0 +1,15 @@
+package tech.cryptonomic.conseil.common.tezos
+
+object Fork {
```
Comment (vishakh) [inline conseil-common/src/main/scala/tech/cryptonomic/conseil/common/tezos/Fork.scala:3]: Curious why this is an object by itself. In the future, what else might it contain other than `mainForkId`?

**Review by vishakh — APPROVED** [review]

File: conseil-common/src/main/scala/tech/cryptonomic/conseil/common/tezos/Fork.scala (hunk 3 above)
Comment (ivanopagano) [reply conseil-common/src/main/scala/tech/cryptonomic/conseil/common/tezos/Fork.scala:3]: I didn't have a proper place to put that constant into.
I did go for a separate object because it's unrelated to other generic tezos operations, essentially.

Also using it at call site explicitly hint at what we're talking about. That is, it's related to fork handling.
